# Generated by Django 5.2.4 on 2025-08-19 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprendices', '0002_aprendizcurso_curso_aprendizcurso_curso_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aprendiz',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name': 'Aprendiz', 'verbose_name_plural': 'Aprendices'},
        ),
        migrations.RemoveField(
            model_name='aprendiz',
            name='Fecha_nacimiento',
        ),
        migrations.AlterField(
            model_name='aprendiz',
            name='apellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='aprendiz',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aprendiz',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='aprendiz',
            name='documento_identidad',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='aprendiz',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='aprendiz',
            name='programa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aprendiz',
            name='telefono',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aprendiz',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
