# Generated by Django 5.2.4 on 2025-08-19 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructor',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name': 'Instructor', 'verbose_name_plural': 'Instructores'},
        ),
        migrations.RenameField(
            model_name='instructor',
            old_name='anos_experiencia',
            new_name='anios_experiencia',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='fecha_registro',
        ),
        migrations.AlterField(
            model_name='instructor',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='correo',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='documento_identidad',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='nivel_educativo',
            field=models.CharField(blank=True, choices=[('TEC', 'Técnico'), ('TGL', 'Tecnólogo'), ('PRE', 'Pregrado'), ('ESP', 'Especialización'), ('MAE', 'Maestría'), ('DOC', 'Doctorado')], default='MAE', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='telefono',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
