# Generated by Django 5.2.4 on 2025-08-07 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='nivel_formacion',
            field=models.CharField(choices=[('AUX', 'Auxiliar'), ('OPE', 'Operario'), ('TEC', 'Técnico'), ('TGL', 'Tecnólogo'), ('ESP', 'Especialización Tecnológica'), ('COM', 'Complementario')], max_length=3, verbose_name='Nivel de Formación'),
        ),
    ]
