# Generated by Django 5.2.4 on 2025-08-19 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0002_alter_programa_nivel_formacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programa',
            name='fecha_registro',
        ),
        migrations.AlterField(
            model_name='programa',
            name='codigo',
            field=models.IntegerField(unique=True, verbose_name='Código del Programa'),
        ),
    ]
